site_name: Tet's Notes
nav:
  - Home: index.md
  - About: about.md
  - Contrubution: contribution.md
  - Notes:
    - 大二上:
      - index: class_notes/2_1/index.md
    - 大二下:
      - index: class_notes/2_2/index.md
      - 形式语言与编译: class_notes/2_2/compile.md

theme:
  name: material
  language: zh
  features:
    - content.tabs.link

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #- javascripts/katex.js
  #- https://unpkg.com/katex@0/dist/katex.min.js
  #- https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css